travis:
  secure:
    BINSTAR_TOKEN: Y/w6AZ6JmM1zl+5Mf2e5XWFpBOuby4WNb4qZEAWQ2Z/sd45OIP2A6lGDLKzVvD/+gJRZqRpTCvvjPXFMxoBVPImNupmosB9VAA99XSmcK67nVbL52NfnomwFR4QKEuhKrITaZKwH4JWkrJa4lNKIskA6JWJsPRFS2qPu5nxIhWCRVflQN5sJUiXqETXajHEeH3sNnQbFFItoDZLrXL5whTDf/v86FuP9a5PqD713dMmW52UdxokGS17QqCsldh+3G0e+UiUTDcwLXba+66B4/AalLkQ7BvttytcLI+hRCSdIdsyDVI1Hy4TgeEmHtsatdBDNrniDmFhzGF0fDi/eFWtOvzlvMQFO57xj77Eb+z1y0H4k15lu9JVaN6lYGpV+4ul8VGYuRe4/9UQg96b7zCwtBLp4KD11bwJVmLXP0gwJZIlqcgW0pWmd+riQ2eYYU0HY6PdXpmsEs9rNNh79mEOG6BT+BvTn4Kp7iwrd9+14U3t55qXDFLzM6KA9IaLDnCQxCqtA8vKHTSRD9thw31q43AoNyNILMfQYklTewPOAbgWxEn9Vy0kfKeqrrvF7FVYZMuid61xkgJKSpjIlw+48xK8p/5bgYL4n2FRPTgI3bmh+HtXPw4MuNucqMIKcCo3q8r9wsG9IMJBY//NQTrsk5p3DmEw8YjGLK9S3j4Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
